# Generated by Django 4.2 on 2023-05-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_details', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('imgs', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('review_count', models.IntegerField()),
                ('reviews', models.CharField(blank=True, max_length=3000, null=True)),
                ('recommended_products', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_products_imgs', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
