# Generated by Django 4.2 on 2023-07-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('original_price', models.TextField(blank=True, null=True)),
                ('discounted_price', models.TextField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('warranty_duration', models.TextField(blank=True, null=True)),
                ('warranty_period', models.TextField(blank=True, null=True)),
                ('warranty_type', models.TextField(blank=True, null=True)),
                ('average_rating', models.TextField(blank=True, null=True)),
                ('num_ratings', models.TextField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('similar_products', models.TextField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('delivery_time_from', models.TextField(blank=True, null=True)),
                ('delivery_time_to', models.TextField(blank=True, null=True)),
                ('delivery_time_period', models.TextField(blank=True, null=True)),
                ('delivery_time_unparsed', models.TextField(blank=True, null=True)),
                ('delivery_fee', models.TextField(blank=True, null=True)),
                ('delivery_details', models.TextField(blank=True, null=True)),
                ('imgs', models.JSONField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('last_updated', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('search_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('search_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('search_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('search_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('search_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('average_rating', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbase.product')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
