# Generated by Django 4.2 on 2023-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
