# Generated by Django 4.2 on 2023-07-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
