# Generated by Django 4.2 on 2023-06-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
