# Generated by Django 4.2 on 2023-05-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
