# Generated by Django 4.2 on 2023-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0004_favourite_searchhistory_viewhistory_visithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateField(auto_now=True),
        ),
    ]
