# Generated by Django 4.2 on 2023-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0006_alter_searchhistory_search_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='search_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='search_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='search_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateField(auto_now=True),
        ),
    ]
