# Generated by Django 4.2 on 2023-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbase', '0007_favourite_search_time_viewhistory_search_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('search_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
